language: cpp
compiler:
  - clang
  - gcc
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install libboost-dev libboost-program-options-dev
script:
  - mkdir build
  - cd build
  - cmake ..
  - make
